#Link
INSERT INTO card(name,idBinder,idType,count) VALUES
("Linguiriboh",2,1,1),
("Black luster soldier - soldier of chaos",2,1,1),
("Geonator transverser",2,1,1),
("Knightmare phoenix",2,1,1),
("Superheavy samurai scarecrow",2,1,1),
("Gouki the powerload ogre",2,1,1),
("Space Insulator",2,1,1),
("Linkerbell",2,1,1),
("Protector of the agents - Moon",2,1,1),
("Vampire sucker",2,1,1),
("Paleozoic cambroraster",2,1,1),
("Sunavalon melias",2,1,1),
("Giant beetrooper invincible atlas",2,1,2),
("Tri-brigade beardrumm the rampant rampager",2,1,1),
("Shinobi insect hagakuremino",2,1,1),
("Underworld goddess of the closed world",2,1,1),
("Abyss keeper",2,1,1);

#XYZ
INSERT INTO card(name,idBinder,idType,count) VALUES
("Number 97: Draglubion",2,2,1),
("Ultimate dragonic utopia ray",2,2,1),
("Plunder patrollship moerk",2,2,1),
("Crimson knight vampire bram",2,2,2),
("D/D/D Duo-dawn king kali yuga",2,2,1),
("Virtual world phoenix - fanfan",2,2,1),
("Joyous melffys",2,2,1),
("Light dragon @ignister",2,2,1),
("Rikka queen strenna",2,2,1),
("Ebon illusion magician",2,2,3),
("Number C88: Gimmick Disaster Leo",2,2,1),
("Ebon high magician",2,2,1),
("Number C15: Gimmick puppet giant hunter",2,2,1),
("Gagagaga Magician",2,2,1),
("Sacred tree beast, hyperyton",2,2,1),
("Gunkan suship ikura-class dreadnought",2,2,1);

#Synchro
INSERT INTO card(name,idBinder,idType,count) VALUES
("Plunder patrollship brann",2,3,1),
("Azure-eyes silver dragon",2,3,1),
("The executor of the underground - Pluto",2,3,2),
("Swordsoul supreme sovereign - chengying",2,3,1),
("Yazi, evil of the yang zing",2,3,1),
("Dragunity knight - Barcha",2,3,1),
("Dragunity knight - Trident",2,3,1),
("Ancient flamvell deity",2,3,1),
("Deep sea repetiteur",2,3,1),
("Flamvell uruquizas",2,3,1),
("Sun dragon Inti",2,3,1),
("Maple maiden",2,3,1),
("Stellar wind wolfrayet",2,3,1),
("Star mine",2,3,1),
("Garden rose flora",2,3,1),
("Moon dragon quilla",2,3,2),
("Accel synchron",2,3,2);

#Fusion
INSERT INTO card(name,idBinder,idType,count) VALUES
("Dinomorphia stealthbergia",2,4,1),
("Starving venom fusion dragon",2,4,2),
("Fossil machine skull wagon",2,4,1),
("Parametalfoes azortless",2,4,2),
("Fossil machine skull buggy",2,4,1),
("Elemental hero sunrise",2,4,1),
("Mystical sand",2,4,2),
("Red-eyes dark dragoon",2,4,1),
("Rare fish",2,4,1),
("Despian proskenion",2,4,1),
("Rose spectre of dunn",2,4,1),
("Predaplant chimerafflesia",2,4,1),
("Elemental HERO neos kluger",2,4,1),
("Rainbow overdragon",2,4,1),
("Naturia exterio",2,4,1),
("Ultimate crystal rainbow dragon overdrive",2,4,1),
("Predaplant triphyoverutum",2,4,2),
("Master of Chaos",2,4,1),
("Predaplant dragostapelia",2,4,3),
("Predaplant ambulomelides ",2,4,1),
("Evil hero wild cyclone",2,4,1),
("Evil hero malicious fiend",2,4,1),
("Evil hero lightning golem",2,4,2),
("Evil hero dark gaia",2,4,3),
("Evil hero infernal sniper",2,4,1);

#Ritual
INSERT INTO card(name,idBinder,idType,count) VALUES
("Magikey mechmortar - garesglasser",2,5,1);

#Effect monster
INSERT INTO card(name,idBinder,idType,count) VALUES
("Mathmech addition",2,6,1),
("Ghostrick siren",2,6,1),
("Ally of justice reverse break",2,6,1),
("Magician's robe",2,6,1),
("Thron the disciplined angel",2,6,1),
("Darkstorm dragon",2,6,1),
("Tenyi spirit - Shthana",2,6,1),
("Mad hacker",2,6,1),
("Dragunity darkspear",2,6,1),
("Dark spirit of banishment",2,6,2),
("Gunkan sunship uni",2,6,1),
("Maiden with eyes of blue",2,6,1),
("Malefic cyber end dragon",2,6,1),
("S-Force lapcewell",2,6,1),
("Motor shell",2,6,1),
("Predaplant chlamydosundew",2,6,2),
("Gizmek taniguku, the immobile intel,lect",2,6,1),
("Magicians' souls",2,6,1),
("Code exporter",2,6,1),
("Electromagnetic turtle",2,6,1),
("The agent of entropy - Uranus",2,6,1),
("Carpiponica, mystical beast of the ,forest",2,6,2),
("Despian tragedy",2,6,1),
("Sky stricker ace - raye",2,6,1),
("Ghostrick jiangshi",2,6,1),
("Submared tour ride",2,6,1),
("Glow-up bloom",2,6,1),
("Gunkan suship ikura",2,6,1),
("Lord of the heavenly prison",2,6,1),
("Swordsoul of taia",2,6,2);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Outburst dragon",2,6,1),
("Epsilon the magnet warrior",2,6,1),
("Tenyi spirit - Vishuda",2,6,1),
("Undaunted bumpkin beast",2,6,1),
("Icejade tremora",2,6,1),
("Incredible ecclesia, the virtous",2,6,1),
("D/D Necro slime",2,6,1),
("Magikuriboh",2,6,1),
("Harpie lady 1",2,6,1),
("Dark honest",2,6,1),
("Live-twin lil-la treat",2,6,1),
("Agido the ancient sentinel",2,6,1),
("Vision HERO gravito",2,6,2),
("Berry magician girl",2,6,1),
("Palladium oracle mahad",2,6,1),
("Floowandereeze & stri",2,6,2),
("Flying red carp",2,6,1),
("Keldo the sacred protector",2,6,1),
("Box of friends",2,6,1),
("Lemon magician girl",2,6,1),
("Timaeus the united dragon",2,6,1),
("Icejade tinola",2,6,1),
("Guitar gurnards duonigis",2,6,1),
("Mudora the sword oracle",2,6,1),
("The agent of creation - Venus",2,6,2),
("Apple magician girl",2,6,1),
("Apprentice illusion magician",2,6,2),
("Windwitch - blizzard bell",2,6,1),
("Sangan",2,6,1),
("Therion 'bull' ain",2,6,1),
("Reptia egg",2,6,2);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Chocolate magician girl",2,6,1),
("Dark necrofear",2,6,2),
("Dark eye nightmare",2,6,1),
("Oracle of the sun",2,6,1),
("Proxy Hourse",2,6,1),
("Kiwi magician girl",2,6,1),
("Dodododwarf gogogoglove",2,6,2),
("Ghost mourner & moonlit chill",2,6,1),
("Ash blossom & joyous spring",2,6,1),
("Cocatorium the heavy metal avian",2,6,1),
("Redbeard, the plunder patroll matey",2,6,1),
("Evil hero malicious edge",2,6,2),
("Yamorimori",2,6,1),
("Ghost belle & haunted mansion",2,6,1),
("Performapal miss director",2,6,2),
("Fabled ashenveil",2,6,1),
("Winged kuriboh",2,6,3),
("Windwitch - freeze bell",2,6,1),
("Hamon, Lord of striking thunder",2,6,1),
("Tenyi spirit - Mapura",2,6,1),
("Samurai of the ice barrier",2,6,1),
("Earthbound immortal chacu challhua",2,6,3),
("Gunkan sunship shirauo",2,6,1),
("Dimension shifter",2,6,1),
("Inzektor hornet",2,6,1),
("Pilgrim of the ice barrier",2,6,1),
("Earthbound linewalker",2,6,3),
("Gizimek inaba, the hopping hare of hakuto",2,6,1),
("Contact 'C'",2,6,1),
("The agent of mystery - Earth",2,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("The fabled kokkator",2,6,1),
("Earthbound immortal ccarayhua",2,6,1),
("Live-twin ki-sikil frost",2,6,1),
("Crystal beast ruby carbuncle",2,6,1),
("Ghostrick mary",2,6,2),
("Geomancer of the ice barrier",2,6,1),
("Earthbound immortal ccapac apu",2,6,1),
("Flip frozen",2,6,1),
("Crystal beast amethyst cat",2,6,1),
("Deskbot 001",2,6,1),
("Ally of justice cycle reader",2,6,1),
("Jowgen the spiritualist",2,6,2),
("Destiny hero - denier",2,6,1),
("Crystal beast emerald tortoise",2,6,1),
("Melffy catty",2,6,1),
("Naturia cosmobeet",2,6,1),
("Evil hero sinister necrom",2,6,2),
("Heavy beetrooper mighty neptune",2,6,2),
("Crystal beast topaz tiger",2,6,1),
("Squaknight",2,6,1),
("The fabled peggulsus",2,6,1),
("Diabound kernel",2,6,2),
("Supay, duskwalker",2,6,1),
("Crystal beast amber mammoth",2,6,1),
("Feedran, the winds of mischief",2,6,1),
("Naturia pumpkin",2,6,1),
("Predaplant heliamphorhynchus",2,6,1),
("Satellite synchron",2,6,2),
("Crystal beast cobalt eagle",2,6,1),
("Buzzsaw shark",2,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Warlock of the ice barrier",2,6,1),
("Earthbound immortal wiraqocha rasca",2,6,1),
("Doomcaliber knight",2,6,2),
("Crystal beast sapphire pegasus",2,6,1),
("Marincess basilalima",2,6,1),
("Naturia butterfly",2,6,1),
("Chaos command magician",2,6,2),
("Archfiend empress",2,6,1),
("Rainbow dark dragon",2,6,1),
("Capricious darklord",2,6,1),
("Naturia dragonfly",2,6,1),
("Magician of dark illusion",2,6,3),
("Bravedrive",2,6,1),
("Crystal beast rainbow dragon",2,6,1),
("Transcicada",2,6,1),
("Fabled soulkius",2,6,1),
("Zubababancho gagagacoat",2,6,1),
("Machina unclaspare",2,6,1),
("Rainbow dragon",2,6,1),
("Dracoon lamp",2,6,1),
("Cyber dragon",2,6,1),
("Magician's rod",2,6,3),
("Slower swallow",2,6,1),
("Hieratic dragon of tefnuit",2,6,1),
("Indulged darklord",2,6,1),
("Dragunity phalanx",2,6,1),
("Dark spirit of malice",2,6,1),
("Eda the sun magician",2,6,1),
("Kaiser glider",2,6,1),
("Awekening of the possessed - Rasenryu",2,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Naturia cherries",2,6,1),
("Neo-spacian aqua dolphin",2,6,1),
("Aeropixthree",2,6,1),
("Raider of the storm winds",2,6,1),
("Awekening of the possessed - Gagigobyte",2,6,1),
("Mist valley executor",2,6,1),
("Necroface",2,6,2),
("Dinowrestler iguanodraka",2,6,1),
("Honest",2,6,1),
("Magical Broker",2,6,1),
("Naturia fruitfly",2,6,1),
("Evil hero infernal gainer",2,6,3),
("Materiactor gigadra",2,6,1),
("Kaiser sea hourse",2,6,1),
("Curse of dragon, the cursed dragon",2,6,1),
("Naturia rosewhip",2,6,1),
("Smoke mosquito",2,6,1),
("Constellar caduceus",2,6,1),
("Herald of creation",2,6,1),
("Soldier Gaia the fierce knight",2,6,1),
("The fabled cerburrel",2,6,1),
("Curse Necrofear",2,6,2),
("The fabled abanc",2,6,1),
("Kaibaman",2,6,1),
("Lifeless leaffish",2,6,1),
("Naturia ragweed",2,6,1),
("Gimmick puppet bisque doll",2,6,1),
("Staysailor romarin",2,6,1),
("The white stone of legend",2,6,1),
("Jack-o-bolan",2,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Secret guards of the ice barrier",2,6,1),
("Predaplant drosophyllum hydra",2,6,2),
("Pharaonic guardian sphinx",2,6,1),
("Divine dragon apocralyph",2,6,1),
("Dimension conjurer",2,6,2),
("Ally of justice cosmic gateway",2,6,1),
("Evil hero adusted gold",2,6,1),
("Ghost sister & spooky dogwood",2,6,1),
("Mirage dragon",2,6,1);

#pendulum
INSERT INTO card(name,idBinder,idType,count) VALUES
("D/D Savant copernicus",2,7,1),
("D/D/D Destiny king zero laplace",2,7,1),
("Fire opal head",2,7,1),
("D/D Savant thomas",2,7,1),
("Performapal celestial magician",2,7,3),
("Anchamoufrite",2,7,1),
("Pazuzule",2,7,1),
("Crystal master",2,7,1),
("Crystal keeper",2,7,1);

#Normal monster
INSERT INTO card(name,idBinder,idType,count) VALUES
("Dark magician",2,8,1),
("Melffy rabby",2,8,1),
("Doll monster bear-bear",2,8,1),
("Obelisk the tormentor",2,8,1),
("Sliffer the sky dragon",2,8,1),
("The winged dragon of ra",2,8,1),
("Flamvell guard",2,8,2),
("Doll monster miss madchen",2,8,1),
("Luster dragon",2,8,1),
("Alexandrite dragon",2,8,1),
("Rabidragon",2,8,1),
("Blue-eyes white dragon",2,8,1);

#Trap
INSERT INTO card(name,idBinder,idType,count) VALUES
("Dark renewal",2,9,1),
("Zoma the spirit",2,9,2),
("Black illusion",2,9,1),
("Magistery alchemist",2,9,2),
("Magikey duo",2,9,1),
("Beetrooper fly & sting",2,9,1),
("Dinomorphia brute",2,9,1),
("Dogmatika genesis",2,9,1),
("Monster rebirth",2,9,1),
("Terrors of the underroot",2,9,1),
("Eternal soul",2,9,1),
("Soul energy MAX!!!",2,9,1),
("Void cauldron",2,9,1),
("Icy breeze refrain",2,9,1),
("Offering to the immortals",2,9,1),
("Destiny board",2,9,1),
("Crystal boon",2,9,1),
("Puppet parade",2,9,1),
("Crystal miracle",2,9,1),
("Earthbound wave",2,9,2),
("Crystal brilliance",2,9,1),
("Ultimate earthbound immortal",2,9,2),
("Crystal pair",2,9,1),
("Call of the earthbound",2,9,2),
("Crystal conclave",2,9,1),
("Magician's circle",2,9,2),
("Ultimate crystal magic",2,9,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Sentence of doom",2,9,3),
("Counter gem",2,9,1),
("D/D/D headhunt",2,9,1),
("Ferret flames",2,9,1),
("End of the line",2,9,1),
("Metaverse",2,9,1),
("Scrap-iron signal",2,9,1),
("Castle of dragon souls",2,9,1),
("Hero signal",2,9,1),
("Champion's vigilance",2,9,1),
("Revival of the immortals",2,9,2),
("Compulsory evacuation device",2,9,1),
("The revived sky god",2,9,1),
("Call of the haunted",2,9,1),
("Magikey unlocking",2,9,1),
(" Damage condenser",2,9,1),
("Armed dragon thunderbolt",2,9,1),
("Kunai with chain",2,9,1),
("Fabled treason",2,9,1),
("Fiendish chain",2,9,1),
("Terrors of the underrot",2,9,1),
("Swordsoul strife",2,9,1),
("Expendable dai",2,9,1),
("Ice dragon's prison",2,9,1),
("Predaplanning",2,9,1),
("Magicians' combination",2,9,2),
("Magician navigation",2,9,2);

#Spell
INSERT INTO card(name,idBinder,idType,count) VALUES
("Yang zing prana",2,10,1),
("Secrets of dark magic",2,10,2),
("Supernatural danger zone",2,10,2),
("The melody of awakening dragon",2,10,1),
("Domain of the true monarchs",2,10,2),
("Earthbound immortal revival",2,10,3),
("Beetrooper landing",2,10,1),
("Foolish burial goods",2,10,1),
("Fossil fusion",2,10,1),
("Supreme king's castle",2,10,2),
("Spirit message 'N'",2,10,1),
("Cosmic cyclone",2,10,1),
("The sanctum of parshath",2,10,1),
("Spirit message 'L'",2,10,2),
("Miracle fusion",2,10,2),
("Crystal bond",2,10,1),
("Heavenly dragon circle",2,10,1),
("Perform puppet",2,10,2),
("Earthbound geoglyph",2,10,1),
("Rainbow bridge of the heart",2,10,1),
("Infernoble arms - Hauteclere",2,10,1),
("Predaponics",2,10,1),
("E - Emergency call",2,10,1),
("Swords of revealing light",2,10,1),
("Ultimate fusion",2,10,2),
("Skyscraper",2,10,3),
("Stairway to a fabled realm",2,10,1),
("Silvers cry",2,10,1),
("A. I. Love fusion",2,10,1),
("Onomatopickup",2,10,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Breath of acclamation",2,10,1),
("Enemy controller",2,10,1),
("Kuji-kiri Curse",2,10,1),
("Branded disciple",2,10,1),
("Book of lunar eclipse",2,10,1),
("Soul exchange",2,10,1),
("Disposable learner device",2,10,1),
("Tuning",2,10,1),
("You and A.I",2,10,1),
("Dragonic tactics",2,10,1),
("Link party",2,10,1),
("Favorite hero",2,10,2),
("Zexal entrust",2,10,1),
("Monster reborn",2,10,1),
("Diced dice",2,10,1),
("Future drive",2,10,1),
("Tri-brigade rendezvous",2,10,1),
("One for one",2,10,1),
("Dogmatikacism",2,10,1),
("Predaplast",2,10,1),
("Sunvine sowing",2,10,1),
("White elephants gifts",2,10,1),
("Witchcrafter unveiling",2,10,1),
("Dark calling",2,10,2),
("Stardust illumination",2,10,1),
("Cards of consonance",2,10,1),
("Fury of kairyu-shin",2,10,1),
("Predapractice",2,10,1),
("Armed dragon lightning",2,10,1),
("A wingbeat of giant dragon",2,10,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Dogmatikamacabre",2,10,1),
("Dark sanctuary",2,10,3),
("A hero lives",2,10,1),
("Stamping destruction",2,10,1),
("The eye of timaeus",2,10,1),
("Icejade cradle",2,10,1),
("R - righteous justice",2,10,1),
("Burst stream of destruction",2,10,1),
("Dark magical circle",2,10,2),
("Trickstar festival",2,10,1),
("Awekening of the crystal ul ultimates",2,10,1),
("Dragon shrine",2,10,1),
("Inzektor sword - zektkaliber",2,10,1),
("Beetrooper descent",2,10,1),
("Crystal Aegis",2,10,1),
("A legendary ocean",2,10,1),
("Evolution burst",2,10,1),
("Greater polymerization",2,10,1),
("Ancient city - rainbow ruins",2,10,1),
("Pendulum call",2,10,1),
("Mystical space typhoon",2,10,1),
("Pendulum treasure",2,10,1),
("Rainbow bridge",2,10,1),
("Sky stricker mobilize - linkage",2,10,1),
("Synchro chase",2,10,3),
("Windwitch chimes",2,10,1),
("Crystal beacon",2,10,1),
("Scapegoat",2,10,1),
("Earthbound whirlwind",2,10,1),
("Magikey maftea",2,10,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Crystal blessing",2,10,1),
("Spirit message 'I'",2,10,1),
("Link into the VRAINS!",2,10,1),
("Crystal abudance",2,10,1),
("Spirit message 'A'",2,10,1),
("Parametalfoes fusion",2,10,1),
("Crystal promise",2,10,1),
("Generation next",2,10,1),
("Armed dragon blitz",2,10,1),
("Crystal tree",2,10,1),
("Illusion magic",2,10,2),
("Live-twin sunnys snitch",2,10,2),
("Crystal release",2,10,1),
("Hero flash!!",2,10,2),
("Bujincandescence",2,10,1),
("Crystal value",2,10,1),
("Smile action",2,10,3),
("The breaking ruin god",2,10,1),
("Rainbow refraction",2,10,1),
("Evil mind",2,10,3),
("Sunvine cross breed",2,10,1),
("Advanced dark",2,10,1);

#Other
INSERT INTO card(name,idBinder,idType,count) VALUES
("Crystal beast token",2,11,1),
("Jesse anderson - bounder with the crystal beast",2,11,1),
("Jesse and ruby - unleashing the legend",2,11,1),
("G Golem token",2,11,2);