INSERT INTO ctypes(type) VALUES
("Link"),
("XYZ"),
("Synchro"),
("Fusion"),
("Ritual"),
("Effect Monster"),
("Pendulum"),
("Normal Monster"),
("Trap"),
("Spell"),
("Other");

INSERT INTO binder(color) VALUES
("Red"),
("Black");

--XYZ
INSERT INTO card(name,idBinder,idType,count) VALUES
("Traptix allomerus",1,2,1),
("Baby tiragon",1,2,1),
("Maestroke the symphony djinn",1,2,1),
("Onibimaru soul sweeper",1,2,2),
("Battlecruiser dianthus",1,2,1),
("Virtual world shell - Jaja",1,2,2),
("Temtempo the percussion Djinn",1,2,1),
("Muzurhythm the string Djinn",1,2,1),
("Melomelody the brass Djinn",1,2,1);

--Synchro
INSERT INTO card(name,idBinder,idType,count) VALUES
("Penguin brave",1,3,2),
("Martial metal marcher",1,3,1),
("Stardust warrior",1,3,1),
("Junk Warrior",1,3,1),
("Angel of zera",1,3,1),
("Vindikite R-Genex",1,3,1),
("Infernoble knight captain roland",1,3,1),
("Groza, tyrant of thunder",1,3,1),
("Catapult warrior",1,3,1),
("Black winged dragon",1,3,1),
("Black brutdrago",1,3,1),
("Gaia Knight, The force of earth",1,3,1),
("X-Saber Urbellum",1,3,1),
("Junk Destroyer",1,3,1),
("Chaos King Archifiend",1,3,1),
("Adamancipator Risen - Dragite",1,3,1),
("Deep sea prima donna",1,3,1),
("Geomathmech final sigma",1,3,1);

--Fusion
INSERT INTO card(name,idBinder,idType,count) VALUES
("Mirrorjade the iceblade dragon",1,4,1),
("Lubellion the searing dragon",1,4,1),
("Titaninklad the ash dragon",1,4,1),
("Brigrand the glory dragon",1,4,2),
("Spring the irondash dragon",1,4,1),
("Albion the branded dragon",1,4,2),
("The shaddoll apkallone",1,4,1),
("Dragonmaid sheou",1,4,1),
("Dark magician the dragon knight",1,4,1);

--Ritual
INSERT INTO card(name,idBinder,idType,count) VALUES
("Chackra",1,5,1);

--Effect Monster
INSERT INTO card(name,idBinder,idType,count) VALUES
("Debris dragon",1,6,1),
("Trident warrior",1,6,1),
("Sand moth",1,6,1),
("Fallen of albaz",1,6,1),
("Helios - The primordial sun",1,6,1),
("Iron chain coil",1,6,1),
("Wingtortoise",1,6,1),
("Springans kitt",1,6,1),
("Gaap the divine soldier",1,6,1),
("Mosaic manticore",1,6,1),
("Barrier statue of the stormwinds",1,6,1),
("Tri-brigade mercourier",1,6,1),
("Volcanic queen",1,6,1),
("Rampaging rhynos",1,6,1),
("Layard the liberator",1,6,1),
("Raviel, lord of phantasms - shimmering scraper",1,6,1),
("Infernity beast",1,6,1),
("Copy plant",1,6,1),
("Feedback warrior",1,6,1),
("Tri-brigade nervall",1,6,1),
("Moja",1,6,1),
("Fortress warrior",1,6,1),
("Gemini scorpion",1,6,1),
("Artillery catapult turtle",1,6,1),
("Arcana force XVIII - The moon",1,6,1),
("Horseytail",1,6,1),
("Giant rat",1,6,1),
("Girsu, the orcust mekk-knight",1,6,1),
("The six samurai - irou",1,6,1),
("Goblin decoy squad",1,6,1),
("Man beast of ares",1,6,1),
("Virtual world xiezhi -jiji",1,6,1),
("Winged Rhynos",1,6,1),
("zombie mammoth",1,6,2),
("Turret warrior",1,6,1),
("Jet synchron",1,6,1),
("Nettles",1,6,1),
("Codaris",1,6,1),
("Key man the key warrior",1,6,2),
("Worm Millidith",1,6,1),
("Tricular",1,6,1),
("Vocanic shell",1,6,1),
("Synchron explorer",1,6,1),
("Allure queen LV3",1,6,1),
("Master gig",1,6,2),
("Quillbolt hedgehog",1,6,2),
("Alien skull",1,6,1),
("Throwstone unit",1,6,1),
("Geargiano",1,6,1),
("Biofalcon",1,6,1),
("Phantom beast cross-wing",1,6,1),
("Tenshin",1,6,1),
("Magic hole golem",1,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Battle fader",1,6,2),
("Gogogo golem",1,6,1),
("Regalus",1,6,1),
("Kycoo the ghost destroyer",1,6,1),
("Stray asmodian",1,6,1),
("Trigon",1,6,1),
("Tuningware",1,6,1),
("Wattwoodpecker",1,6,1),
("Reptilianne servant",1,6,1),
("Simorgh, birth of calamity",1,6,1),
("Dark bug",1,6,1),
("Dark tinker",1,6,1),
("Dinomorphia diplos",1,6,2),
("Majestic dragon",1,6,1),
("Spyder spider",1,6,1),
("Infernity wildcat",1,6,3),
("Quickdraw synchron",1,6,3),
("Diana the light spirit",1,6,3),
("Spined gillman",1,6,1),
("X-Saber Galahad",1,6,1),
("Koa'ki meiru hydro barrier",1,6,1),
("Hayabusa Knight",1,6,1),
("Zubaba Knight",1,6,1),
("Gadget arms",1,6,1),
("Infernity conjurer",1,6,3),
("Changer Synchron",1,6,1),
("Lava dragon",1,6,1),
("Nowru aries the vernal dragon",1,6,2),
("Koa'ki Meiru Urnight",1,6,1),
("Spore",1,6,3),
("Van'Dalgyon the dark dragon lord",1,6,1),
("Ground spider",1,6,1),
("The six samurai - Nisashi",1,6,1),
("Hammer Bounzer",1,6,1),
("Izanami",1,6,1),
("Gragonith, lightstorm dragon",1,6,1),
("Healing Wave generator",1,6,1),
("Magidog",1,6,1),
("Gigastone omega",1,6,1),
("Field-commander Rahz",1,6,1),
("Second booster",1,6,1),
("Spirit of the six samurai",1,6,1),
("Man-eater Bug",1,6,2),
("Card breaker",1,6,1),
("Omni dragon brotaur",1,6,1),
("Cactus fighter",1,6,1),
("Dark spider",1,6,1),
("Effect veiler",1,6,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Shine knight",1,6,1),
("Blackwing - ghibli the searing wind",1,6,1),
("Ghost ogre & snow rabbit",1,6,2),
("Worm apocalypse",1,6,1),
("Power invader",1,6,1),
("Summoner monk",1,6,1),
("speed warrior",1,6,1),
("Rose fairy",1,6,1),
("Keeper of dragon magic",1,6,1),
("Twin-sword marauder",1,6,1),
("Cyber tutu",1,6,1),
("Starliege seyfert",1,6,1),
("Speed bird",1,6,1),
("Vengeful shinobi",1,6,1),
("Black dragon collapserpent",1,6,1),
("Power injector",1,6,1),
("Gundari",1,6,1),
("White dragon wyverbuster",1,6,1),
("Warrior Lady of the Wastland",1,6,1),
("Oilman",1,6,1),
("Artifact scythe",1,6,1),
("Ganbara Knight",1,6,1),
("Des Frog",1,6,1),
("Radian, the multidimensional kaiju",1,6,1),
("Rockstone warrior",1,6,1),
("Relinquished spider",1,6,2),
("Chaos dragon levianeer",1,6,1),
("Marauding captain",1,6,1),
("Shining angel",1,6,3),
("Thunder king, the lightningstrike kaiju",1,6,1),
("Psychic jumper",1,6,1),
("Chainsaw insect",1,6,1),
("Red-eyes darkness metal dragon",1,6,1),
("Junk Synchron",1,6,2),
("Reptilianne Gardna",1,6,1),
("Dogmatika fleurdelis, the knighted",1,6,2),
("Blade Knight",1,6,1),
("Bicular",1,6,1),
("Albion the shrouded dragon",1,6,1),
("Princess pikeru",1,6,1),
("Barrier Statue of the torrent",1,6,1),
("The golden swordsoul",1,6,1);

--Pendulum
INSERT INTO card(name,idBinder,idType,count) VALUES
("D/D Savant nikola",1,7,2),
("Dinomist plesios",1,7,1),
("Performapal bubblebowwow",1,7,1),
("Performapal lizardraw",1,7,1),
("Dinomist ceratops",1,7,1),
("Rain bozu",1,7,1),
("Metalfoes steelen",1,7,1),
("Dragong",1,7,1),
("Sea dragoons of draconia",1,7,1);

--Normal Monster
INSERT INTO card(name,idBinder,idType,count) VALUES
("Spirit of the harp",1,8,2),
("Luster dragon #2",1,8,2),
("Gene-warped warwolf",1,8,1),
("Ally mind",1,8,2),
("Dark blade",1,8,1),
("Left arm of the forbidden one",1,8,1),
("Blazing inpachi",1,8,1),
("Mystic clown",1,8,1),
("Sea serpent warrior of darkness",1,8,1),
("Root water",1,8,1),
("Kojikocy",1,8,1),
("Dragon zombie",1,8,1),
("Giant soldier of stone",1,8,1),
("Swordsman of landstar",1,8,1),
("Doma the angel of silence",1,8,1),
("Flying kamakiri #2",1,8,1),
("Magical ghost",1,8,1),
("Master & expert",1,8,1);

--Trap
INSERT INTO card(name,idBinder,idType,count) VALUES
("Rainbow gravity",1,9,1),
("Skull lair",1,9,1),
("Nightmare archifiends",1,9,1),
("Raging cloudian",1,9,1),
("Threatening roar",1,9,1),
("Level retuner",1,9,2),
("Flamvell counter",1,9,2),
("Just desserts",1,9,1),
("XYZ effect",1,9,2),
("Tour of doom",1,9,1),
("Giant trap hole",1,9,1),
("Return of the six samurai",1,9,1),
("D - fortune",1,9,1),
("Spatial collapse",1,9,1),
("Attack of the cornered rat",1,9,1),
("An unfortunate report",1,9,1),
("Spacegate",1,9,1),
("Slip of fortune",1,9,1),
("Scull lair",1,9,1),
("Ultimate offering",1,9,1),
("Zero force",1,9,1),
("The revenge of the normal",1,9,2),
("Poseidon wave",1,9,1),
("Reckoned",1,9,1),
("Seven tools of the bandit",1,9,2),
("Assault spirits",1,9,1),
("Icejade erosion",1,9,2),
("Lineage of destruction",1,9,1),
("Proof of powerlessness",1,9,1),
("Branded sword",1,9,1),
("Reinforced space",1,9,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("D. D. Dynamite",1,9,1),
("Branded retribution",1,9,1),
("Morphotronic monitron",1,9,1),
("Automatic laser",1,9,1),
("Screams of the branded",1,9,1),
("Shield spear",1,9,1),
("Dinomorphia shell",1,9,1),
("Judgment of the branded",1,9,2),
("Treaty on uniform nomenclature",1,9,1),
("Reckless greed",1,9,1),
("Necro fusion",1,9,1),
("Bamboo scrap",1,9,1),
("Backup soldier",1,9,1),
("Back to the front",1,9,1),
("Straight flush",1,9,1),
("Tribe drive",1,9,1),
("Waring point",1,9,1),
("Revival gift",1,9,1),
("Stronghold the moving fortress",1,9,1),
("There can be only one",1,9,1),
("Plant food chain",1,9,1),
("Spiritual earth art - Kurogane",1,9,1),
("Dimensional barrier",1,9,1),
("DNA checkup",1,9,1),
("Bone temple block",1,9,2),
("Waking the dragon ",1,9,1),
("Reinforce truth",1,9,1),
("Skull invitation",1,9,1),
("Witchcrafter patronus",1,9,1),
("Dust tornado",1,9,3),
("Swallow flip",1,9,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Darklord uprising",1,9,1),
("Lair wire",1,9,1),
("Berserking",1,9,1),
("Horn of olifant",1,9,1),
("Limit reverse",1,9,1),
("Waboku",1,9,2),
("Adamancipator resonance",1,9,1),
("Rope of lif",1,9,2),
("Shadow Impulse",1,9,1),
("Explosive urchin",1,9,1),
("Infinite dismissal",1,9,1),
("Fake feather",1,9,1),
("Virus cannon",1,9,1),
("Generation shift",1,9,1),
("Miniaturize",1,9,1),
("Conscription",1,9,1),
("Trap hole",1,9,1),
("Tuner capture",1,9,2),
("Half or nothing",1,9,1);

--Spell
INSERT INTO card(name,idBinder,idType,count) VALUES
("Card destruction",1,10,1),
("Last will",1,10,1),
("Verdant sanctuary",1,10,1),
("Book of secret arts",1,10,2),
("Final destiny",1,10,1),
("randed disciple",1,10,1),
("Molting escape",1,10,1),
("Hammer shot",1,10,1),
("Psychic path",1,10,1),
("Heavy storm",1,10,1),
("Giant trunade",1,10,1),
("Wonder clover",1,10,1),
("Blustering winds",1,10,1),
("Release restraint wave",1,10,1),
("Iron core immediate disposal",1,10,2),
("Fissure",1,10,2),
("Advance force",1,10,1),
("Vengful servant",1,10,1),
("Solidarity",1,10,1),
("Sword of sparkles",1,10,1),
("Dragon ravine",1,10,1),
("Poison chain",1,10,1),
("Gladiator beast's battle gladius",1,10,1),
("Terraforming",1,10,1),
("Reinforcement of the army",1,10,1),
("Urgent synthesis",1,10,1),
("Dark ruler no more",1,10,2),
("Burden of the mighty",1,10,1),
("Hydro pressure cannon",1,10,1),
("Called by the grave",1,10,1),
("Half shut",1,10,1);

INSERT INTO card(name,idBinder,idType,count) VALUES
("Duelist alliance",1,10,1),
("Pot of extravangance",1,10,1),
("Monster reincarnation",1,10,1),
("Natural tune",1,10,1),
("Gold sarcophagus",1,10,1),
("Teleport",1,10,1),
("Book of eclipse",1,10,1),
("Fusion substitute",1,10,1),
("Fragrance storm",1,10,1),
("Exile of the wicked",1,10,1),
("Fusion gate",1,10,1),
("The warrior returning alive",1,10,2),
("Shien's castle fo mist",1,10,1),
("Fusion recycling plant",1,10,1),
("XYZ energy",1,10,1),
("Mind trust",1,10,2),
("Branded lost",1,10,1),
("Corridor of agony",1,10,1),
("Koa'ki meiru initialize!",1,10,2),
("Branded in white",1,10,1),
("Harmonic waves",1,10,1),
("Nobleman of Crossout",1,10,1),
("Branded bond",1,10,1),
("Banner of courage",1,10,1),
("Viper rebirth",1,10,1),
("Branded fusion",1,10,1),
("Wattcube",1,10,1),
("Pendulum fusion",1,10,1),
("Triple tactics talent",1,10,1),
("Spider web",1,10,1),
("Resurection of chakra",1,10,1),
("Spiral fusion",1,10,1);

--Other
INSERT INTO card(name,idBinder,idType,count) VALUES
("Albaz the shrouded",1,11,1),
("Ecclesia the exiled",1,11,1),
("Tri-brigade",1,11,1),
("The virtuous vestals",1,11,1),
("Aluber the dogmatic",1,11,1),
("Token (Yugi)",1,11,1),
("Set sail for the kingdom",1,11,1),
("Duelist kingdom",1,11,1),
("Glory of the king's hand",1,11,1);